name: Markdown checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/markdownlint.yml
      - .markdownlint.yaml
      - '**.md'

permissions:
  contents: read

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: install markdownlint
      run: sudo npm install -g markdownlint-cli

    - name: run markdownlint
      run: markdownlint '**.md' --ignore 'node_modules/**'
